### ISSUE TITLE
Vyos-AMI change hostname

### ISSUE THREAD

**Issue by scottemackenzie** [hydrajump/vyos-build-ami#1]
Note to improve build.

After loading the AMI and logging in with default vyos@ user I switched to configure mode to change the hostname.  The commit kept failing as "vyos" user.  After changing root password and then switching to root I was able to commit the change and save the configuration.

vyos@VyOS-AMI# set system host-name cmnet04

  Set failed

[edit]

After changing permissions From: 

root@cmnet04:/opt/vyatta/config# ls -la active/
total 0
drwxrwxr-x  5 root vyattacfg 100 Jul  2 18:03 .
drwxrwxr-x  4 root vyattacfg 100 Jul  2 17:48 ..
drwxrwxr-x  4 root root       80 Jul  2 18:03 interfaces
drwxrwxr-x  3 root root       60 Jul  2 18:03 service
drwxrwxr-x 10 root root      200 Jul  2 18:03 system

TO:

vyos@cmnet04:/opt/vyatta/config$ ls -la active/
total 0
drwxrwxr-x  5 root vyattacfg 100 Jul  2 18:03 .
drwxrwxr-x  4 root vyattacfg 100 Jul  2 17:48 ..
drwxrwxr-x  4 root vyattacfg  80 Jul  2 18:03 interfaces
drwxrwxr-x  3 root vyattacfg  60 Jul  2 18:03 service
drwxrwxr-x 10 root vyattacfg 200 Jul  2 18:03 system

The VyOS user is now able to save configuration changes.

**Comment by m0kct** [comment]
This is caused by the ec2-fetch-ssh-public-key script.

The following patch fixed it for me (not sure about that "doesn't work" comment, seems to work for me...):

diff --git a/ec2-fetch-ssh-public-key b/ec2-fetch-ssh-public-key
index 342a8ed..b9ce802 100755
--- a/ec2-fetch-ssh-public-key
+++ b/ec2-fetch-ssh-public-key
@@ -22,7 +22,6 @@ source $vyatta_env

 # Configuration commands
 SHELL_API=/bin/cli-shell-api
-COMMIT=/opt/vyatta/sbin/my_commit
 SAVE=/opt/vyatta/sbin/vyatta-save-config.pl
 LOADKEY=/opt/vyatta/sbin/vyatta-load-user-key.pl

@@ -51,25 +50,11 @@ fi

 load_ssh_public_key ()
 {
-    # Doesn't work.
-    # if [ -x $vyatta_sbindir/vyatta-load-user-key.pl ]; then
-    #     log_action_msg "Loaded ssh public key for user $username"
-    #     sg ${group} -c "$vyatta_sbindir/vyatta-load-user-key.pl $username $public_key"

## \-    # fi
-    # Do this instead
-    # Obtain session environment
-    # Evaluate environment string
-    # Setup the session
-    # Commit and save config change

## \-    # Tear down the session

```
 log_action_msg "EC2: Loaded ssh public key for user $username"
```
-    $LOADKEY $username $public_key_url
-    sg ${group} -c "$LOADKEY $username $public_key_url"
-    # Commit and save to config.boot
-    $COMMIT
-    $SAVE
-    # Save to config.boot
-    sg ${group} -c "$SAVE"
  }
  
  # Try to get the ssh public key from instance metadata
